### ISSUE TITLE
Basic Users

### ISSUE THREAD

**Issue by rennanoliveira** [rennanoliveira/collab-cards#5]
Basic User model.
Without any authentication columns. We plan on using Devise/Omniauth, but thats another issue

**Comment by bschettino** [comment]
When you say that this basic version doesn't have any auth columns I think that, for now, this User model will act as the Author of a card, am I right?
Which attributes this model must have in the basic version?
I'm thinking that, just for the authorship of a card, just name and e-mail are enough to do it.
Am I missing something?

**Comment by rennanoliveira** [comment]
Username and email should work.
I didn't place email there because, lets say we decide upon login with facebook/twitter and the likes, we dont have an email. The email is pretty much a part of the authentication decision, so I was going to place that when we actually started on the login process
