### ISSUE TITLE
Add Code Quality rules/checks to our project.

### ISSUE THREAD

**Issue by rennanoliveira** [rennanoliveira/collab-cards#9]
What should we use for code quality? Code style guides and Rubocop?

**Comment by igorbp** [comment]
RuboCop is great to enforce many of the guidelines from the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide), as stated in its own README file. Also it's highly configurable. We should consider using [Code Climate](https://codeclimate.com/) too. It's free for open source repos.

**Comment by rennanoliveira** [comment]
RuboCop it is, then. I'll open a separate ticket for Code Climate (or you can, too)
